import Footer from "@/components/footer/footer";
import { Victor_Mono } from "next/font/google";
import "./globals.scss";
import Nav from "@/components/nav/nav";

const victorMono = Victor_Mono({
  subsets: ["latin"],
  display: "swap",
  fallback: ["monospace"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={victorMono.className}>
        <div className="main">
          <Nav />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
